force-app/Exercises/main/default/objects/Certification_Attempt__c/Certification_Attempt__c.object-meta.xml
<CustomObject>
    <label>Certification Attempt</label>
    <nameField>
        <displayFormat>ATTEMPT-{00000}</displayFormat>
        <label>Certification Attempt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certification Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/Exercises/main/default/objects/Certification_Attempt__c/fields/Certification_Candidate__c.field-meta.xml
<CustomField>
    <fullName>Certification_Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certification Attempts</relationshipLabel>
    <relationshipName>Certification_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/Exercises/main/default/objects/Certification_Attempt__c/fields/Certification_Element__c.field-meta.xml
<CustomField>
    <fullName>Certification_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Element</label>
    <referenceTo>Certification_Element__c</referenceTo>
    <relationshipLabel>Certification Attempts</relationshipLabel>
    <relationshipName>Certification_Attempts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/Exercises/main/default/objects/Certification_Attempt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete/Pass</fullName>
            </value>
            <value>
                <fullName>Complete/Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/Exercises/main/default/classes/AccountDisplayCertAttempts_CX.cls
public with sharing class AccountDisplayCertAttempts_CX {

    private final Account acct;

    public AccountDisplayCertAttempts_CX(ApexPages.StandardController stdController) {
        this.acct = (Account) stdController.getRecord();
    }

    public List<Certification_Attempt__c> results {
        get {
            if (results == null) {
                results = new List<Certification_Attempt__c>([
                    SELECT Name, Certification_Candidate__r.Name, Certification_Element__r.Name
                      FROM Certification_Attempt__c
                     WHERE Certification_Candidate__r.AccountId = :acct.Id
                       AND Status__c NOT IN ('Complete/Pass', 'Complete/Fail')
                ]);
            }
            return results;
        }
        private set;
    }

}